# Generated by Django 4.2 on 2023-05-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("patronomic", models.CharField(max_length=255)),
                ("birth_date", models.DateField()),
                ("passport_series_number", models.CharField(max_length=20)),
                ("passport_issue_date", models.DateField()),
                ("passport_issued_by", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("driving_number", models.CharField(max_length=20)),
                ("driver_license_issue_date", models.DateField()),
                ("driver_license_valid_until", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
