# Generated by Django 4.2.7 on 2024-01-04 00:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="birth_date",
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="client",
            name="driver_license_issue_date",
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="client",
            name="driver_license_valid_until",
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name="client",
            name="passport_issue_date",
            field=models.DateTimeField(default=datetime.datetime(1990, 1, 1, 0, 0)),
        ),
    ]
