# Generated by Django 4.2.7 on 2024-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_alter_client_birth_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="address",
            field=models.CharField(max_length=100, verbose_name="Улица, дом, квартира"),
        ),
    ]
