# Generated by Django 4.2.7 on 2024-02-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contracts", "0002_alter_contract_amount_alter_contract_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contract",
            name="rental_days",
            field=models.PositiveIntegerField(),
        ),
    ]
