# Generated by Django 4.2.7 on 2023-11-22 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_alter_task_uploaded_file"),
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_files",
                to="tasks.task",
            ),
        ),
    ]
