# Generated by Django 4.2.7 on 2023-11-24 18:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0002_uploadedfile_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadedfile",
            name="task",
        ),
    ]
