# Generated by Django 4.2 on 2023-04-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Регистрация')),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(default='Имя исполнителя', on_delete=django.db.models.deletion.PROTECT, related_name='worker_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
