# Generated by Django 4.2 on 2023-05-19 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='worker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='worker_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
