# Generated by Django 4.2.7 on 2023-11-22 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0001_initial"),
        ("tasks", "0007_remove_taskexecution_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="uploads.uploadedfile",
            ),
        ),
    ]
