# Generated by Django 4.2.7 on 2023-11-24 17:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_alter_task_uploaded_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="uploaded_file",
        ),
    ]
