# Generated by Django 4.2.7 on 2023-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0003_remove_uploadedfile_task"),
        ("tasks", "0010_remove_task_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="uploaded_files",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks_uploaded_files",
                to="uploads.uploadedfile",
            ),
        ),
    ]
