# Generated by Django 4.2.7 on 2023-11-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0003_remove_uploadedfile_task"),
        ("tasks", "0011_task_uploaded_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="uploaded_files",
            field=models.ManyToManyField(blank=True, to="uploads.uploadedfile"),
        ),
    ]
