# Generated by Django 4.2.7 on 2023-11-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_alter_task_uploaded_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="uploaded_files",
        ),
        migrations.AddField(
            model_name="task",
            name="uploaded_files",
            field=models.FileField(blank=True, upload_to="uploads/"),
        ),
    ]
