# Generated by Django 4.2.7 on 2023-11-25 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0013_remove_task_uploaded_files_task_uploaded_files"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="uploaded_files",
            new_name="uploaded_file",
        ),
    ]
