# Generated by Django 4.2.7 on 2023-11-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0014_rename_uploaded_files_task_uploaded_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="task",
            name="uploaded_file",
        ),
        migrations.AddField(
            model_name="task",
            name="uploaded_files",
            field=models.ManyToManyField(blank=True, to="tasks.uploadedfile"),
        ),
    ]
