# Generated by Django 4.2.7 on 2023-11-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0015_uploadedfile_remove_task_uploaded_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="uploaded_files",
        ),
        migrations.AddField(
            model_name="task",
            name="uploaded_file",
            field=models.FileField(blank=True, upload_to="uploads/"),
        ),
        migrations.DeleteModel(
            name="UploadedFile",
        ),
    ]
