# Generated by Django 4.2.7 on 2023-11-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0018_taskexecutionfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecutionfile",
            name="task_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="xfiles",
                to="tasks.taskexecution",
            ),
        ),
    ]
