# Generated by Django 4.2.7 on 2024-01-04 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0019_alter_taskexecutionfile_task_execution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="taskexecutionfile",
            name="task_execution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="xfiles",
                to="tasks.taskexecution",
            ),
        ),
        migrations.AlterField(
            model_name="taskfile",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="file",
                to="tasks.task",
            ),
        ),
    ]
