# Generated by Django 4.2.7 on 2024-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0021_alter_taskexecution_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskexecution",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
