# Generated by Django 4.2.10 on 2024-02-19 18:49

from django.db import migrations, models
import django.utils.timezone
import tasks.validators


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0023_alter_task_created_by_alter_task_worker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[tasks.validators.validate_future_date],
            ),
        ),
        migrations.AlterField(
            model_name="taskexecution",
            name="deadline",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                validators=[tasks.validators.validate_future_date],
            ),
        ),
    ]
