version: '3.8'

services:
  db:
      image: postgres:latest
      volumes:
        - /var/lib/postgresql/data/
      env_file:
        - ./.env
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
