# Generated by Django 4.2.7 on 2024-01-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tariff",
            name="deposit",
            field=models.DecimalField(decimal_places=2, default=6000, max_digits=6),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="price_15_30_days",
            field=models.DecimalField(decimal_places=2, default=300, max_digits=6),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="price_2_3_days",
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=6),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="price_4_7_days",
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=6),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="price_8_14_days",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
        migrations.AlterField(
            model_name="tariff",
            name="price_per_day",
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=6),
        ),
    ]
